// Generated by scripts/generate-blog-registry.mjs. Do not edit manually.
import type { ComponentType } from "react";

import type { ArticleMetadata } from "@/lib/blog/schema";
import Article0, { metadata as article0Metadata } from "./ai-agent-governance-checklist.mdx";
import Article1, { metadata as article1Metadata } from "./ai-automation-cost.mdx";
import Article2, { metadata as article2Metadata } from "./ai-implementation-roadmap.mdx";
import Article3, { metadata as article3Metadata } from "./ibm-ai-transformation-work-redesign.mdx";
import Article4, { metadata as article4Metadata } from "./monitor-ai-agents-in-production.mdx";

export type RegisteredArticle = {
  metadata: ArticleMetadata;
  Component: ComponentType;
};

export const articleRegistry = [
  {
    metadata: article0Metadata,
    Component: Article0,
  },
  {
    metadata: article1Metadata,
    Component: Article1,
  },
  {
    metadata: article2Metadata,
    Component: Article2,
  },
  {
    metadata: article3Metadata,
    Component: Article3,
  },
  {
    metadata: article4Metadata,
    Component: Article4,
  },
] as const satisfies readonly RegisteredArticle[];
